### ISSUE TITLE
ImportError: No module named sliding_window

### ISSUE THREAD

**Issue by YinghaoHuang91** [wilfer9008/CNN_IMU#3]
Hi, when I tried your code, I had this import error like shown below:
```
Traceback (most recent call last):
  File "main.py", line 17, in <module>
    from Network_selecter import Network_selecter 
  File "CNN_IMU/CNN_IMU_rep/src/Network_selecter.py", line 13, in <module>
    from Network_user import Network_user
  File "CNN_IMU/CNN_IMU_rep/src/Network_user.py", line 16, in <module>
    from sliding_window import sliding_window
ImportError: No module named sliding_window
```
Did I miss something here? I hope you can shed some light. 

Thanks!

**Comment by wilfer9008** [comment]
Hi
Thank you very much for finding the error. The module has been uploaded to the rep.

Best regards,
Fernando

**Comment by YinghaoHuang91** [comment]
Thanks for your prompt response! And I used the script to process the PAMAP2 dataset, then changed the path in file Network_user.py from 
```
866             X_train, y_train, X_val, y_val, X_test, y_test = self.load_dataset('/data/fmoya/HAR/pamap2/train_val_test_dataset_pamap2_12_classes_norm.data')
```
to
```
866             X_train, y_train, X_val, y_val, X_test, y_test = self.load_dataset('./pamap2.data')
```
Where pamap2.data is the generated file from the pre-processing script. Then comes this error:

```
Statistics {0: 739, 1: 2561, 2: 2457, 3: 2510, 4: 3227, 5: 1141, 6: 2184, 7: 2446, 8: 1573, 9: 1422, 10: 2337, 11: 3043}
EA_iter 0 Testing network...
Test: Loading weights
EA_iter 0 network file does not exist
Traceback (most recent call last):
  File "main.py", line 162, in <module>
    main()
  File "main.py", line 151, in main
    net_selecter.net_selecter()
  File "CNN_IMU/CNN_IMU_rep/src/Network_selecter.py", line 109, in net_selecter
    self.test()
  File "CNN_IMU/CNN_IMU_rep/src/Network_selecter.py", line 87, in test
    train_test_modus = 2)
  File "CNN_IMU/CNN_IMU_rep/src/Network_user.py", line 930, in evaluating_attr
    acc_net_val, acc_f1_val, percentage_test, deep_descriptor_test, y_used_test = self.test_dist(X_test, y_test, ea_itera, in_train = True)
TypeError: 'float' object is not iterable

```

Any hint about how to solve this issue?

**Comment by guowenhao787938711** [comment]
I have the same problem, have you solved it?

**Comment by David-Gwo** [comment]
your weights is not found! pleas check path.

**Comment by YinghaoHuang91** [comment]
Thanks!
